version: 0.12.5

phases:
  build:
    commands:
    - go get .
    - go build main.go
    - mv main dean
    - tar -czvf dean.tar.gz dean
  post_build:
    commands:
    - echo Build completed on `date`
artifacts:
  files:
  - dean.tar.gz
