version: 0.2

phases:
  build:
    commands:
    - echo Build started on `date`
    - go get .
    - go build main.go
    - mv main dean
    - tar -czvf dean.tar.gz dean
  post_build:
    commands:
    - echo Build completed on `date`
artifacts:
  files:
  - dean.tar.gz
